name: Build and Release

permissions:
  contents: write
  actions: write
  attestations: write
  checks: write
  deployments: write
  discussions: write
  issues: write
  packages: write
  pages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

on:
  workflow_dispatch:
  repository_dispatch:
    types: [new-mod-release]
  push:
    branches:
      - main
      - dev_new
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.25.0'
      - name: Get dependencies
        run: go mod download
      - name: Get version
        id: version
        run: |
          if [ "${{ github.event_name }}" = "release" ]; then
            VERSION="${{ github.ref_name }}"
          else
            VERSION="${GITHUB_SHA:0:8}"
          fi
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Build amd64
        run: |
          GOARCH=amd64 GOEXPERIMENT=jsonv2 go build -ldflags="-X github.com/ouyangmland/V2bX-singbox/cmd.version=${VERSION} -s -w" -o "V2bX-linux-amd64" .
          ls -lh V2bX-linux-amd64
      - name: Build arm64
        run: |
          GOARCH=arm64 GOEXPERIMENT=jsonv2 go build -ldflags="-X github.com/ouyangmland/V2bX-singbox/cmd.version=${VERSION} -s -w" -o "V2bX-linux-arm64" .
          ls -lh V2bX-linux-arm64
      - name: Prepare amd64
        run: |
          mkdir -p build_amd64
          cp README.md LICENSE build_amd64/ 2>/dev/null || true
          cp example/*.json build_amd64/ 2>/dev/null || true
          cp V2bX-linux-amd64 build_amd64/V2bX
          cd build_amd64
          zip -9vr "../V2bX-linux-amd64.zip" . -x "*.DS_Store"
      - name: Prepare arm64
        run: |
          mkdir -p build_arm64
          cp README.md LICENSE build_arm64/ 2>/dev/null || true
          cp example/*.json build_arm64/ 2>/dev/null || true
          cp V2bX-linux-arm64 build_arm64/V2bX
          cd build_arm64
          zip -9vr "../V2bX-linux-arm64.zip" . -x "*.DS_Store"
      - name: Upload amd64
        uses: actions/upload-artifact@v4
        with:
          name: V2bX-linux-amd64
          path: ./V2bX-linux-amd64.zip
      - name: Upload arm64
        uses: actions/upload-artifact@v4
        with:
          name: V2bX-linux-arm64
          path: ./V2bX-linux-arm64.zip
      - name: Release
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./V2bX-linux-amd64.zip,./V2bX-linux-arm64.zip
          tag: ${{ github.ref }}
